# One-time script to extract HLL++ bias correction data from the Go reference implementation
# and generate an Elixir module with the data as tuples of tuples.
#
# Usage:
#   curl -sL https://raw.githubusercontent.com/clarkduvall/hyperloglog/refs/heads/master/data.go -o /tmp/hll_data.go
#   mix run scripts/extract_bias_data.exs /tmp/hll_data.go
#
# Source: github.com/clarkduvall/hyperloglog/blob/master/data.go

input_path =
  case System.argv() do
    [path] -> path
    _ -> raise "Usage: elixir scripts/extract_bias_data.exs <path-to-data.go>"
  end

source = File.read!(input_path)

# Parse a Go 2D float64 array into a list of lists of floats.
# Expects the format: varName = [N][]float64{ {v1, v2, ...}, {v1, v2, ...}, ... }
parse_go_2d_array = fn source, var_name ->
  # Find the variable declaration
  pattern = ~r/#{Regex.escape(var_name)}\s*=\s*\[\]\[\]float64\{(.*?)\n\}/s
  [_, inner] = Regex.run(pattern, source)

  # Extract each sub-array between { and }
  Regex.scan(~r/\{([^}]+)\}/, inner)
  |> Enum.map(fn [_, values_str] ->
    values_str
    |> String.split(",")
    |> Enum.map(&String.trim/1)
    |> Enum.reject(&(&1 == ""))
    |> Enum.map(fn s ->
      {f, ""} = Float.parse(s)
      f
    end)
  end)
end

raw_estimate_data = parse_go_2d_array.(source, "rawEstimateData")
bias_data = parse_go_2d_array.(source, "biasData")

# Verify we got 15 precision levels (4-18)
15 = length(raw_estimate_data)
15 = length(bias_data)

# Verify parallel structure
Enum.zip(raw_estimate_data, bias_data)
|> Enum.with_index(4)
|> Enum.each(fn {{raw, bias}, p} ->
  if length(raw) != length(bias) do
    raise "Mismatch at precision #{p}: #{length(raw)} raw vs #{length(bias)} bias"
  end

  IO.puts("Precision #{p}: #{length(raw)} entries")
end)

# Format a list of floats as an Elixir tuple literal
format_tuple = fn values ->
  formatted =
    values
    |> Enum.map(&:erlang.float_to_binary(&1, decimals: 10))
    |> Enum.chunk_every(6)
    |> Enum.map(&Enum.join(&1, ", "))
    |> Enum.join(",\n        ")

  "{#{formatted}}"
end

# Generate the Elixir module
raw_estimate_tuples =
  raw_estimate_data
  |> Enum.with_index(4)
  |> Enum.map(fn {data, p} ->
    "    # precision #{p} (#{length(data)} entries)\n    #{format_tuple.(data)}"
  end)
  |> Enum.join(",\n")

bias_tuples =
  bias_data
  |> Enum.with_index(4)
  |> Enum.map(fn {data, p} ->
    "    # precision #{p} (#{length(data)} entries)\n    #{format_tuple.(data)}"
  end)
  |> Enum.join(",\n")

module_source = """
defmodule Fate.Cardinality.HyperLogLog.BiasData do
  @moduledoc false
  # Empirical bias correction data for HyperLogLog++ (Heule et al. 2013).
  # Source: https://github.com/clarkduvall/hyperloglog/blob/master/data.go
  # Generated by scripts/extract_bias_data.exs — do not edit manually.

  # Threshold values indexed by (precision - 4).
  # If linear_counting_estimate <= threshold, prefer linear counting.
  @threshold {10, 20, 40, 80, 220, 400, 900, 1800, 3100, 6500, 11_500, 20_000, 50_000, 120_000, 350_000}

  # Sorted raw estimate values per precision, indexed by (precision - 4).
  @raw_estimate_data {
#{raw_estimate_tuples}
  }

  # Bias values parallel to @raw_estimate_data, indexed by (precision - 4).
  @bias_data {
#{bias_tuples}
  }

  @spec threshold(4..18) :: non_neg_integer()
  def threshold(precision) when precision >= 4 and precision <= 18 do
    elem(@threshold, precision - 4)
  end

  @spec raw_estimates(4..18) :: tuple()
  def raw_estimates(precision) when precision >= 4 and precision <= 18 do
    elem(@raw_estimate_data, precision - 4)
  end

  @spec biases(4..18) :: tuple()
  def biases(precision) when precision >= 4 and precision <= 18 do
    elem(@bias_data, precision - 4)
  end

  @spec table_size(4..18) :: non_neg_integer()
  def table_size(precision) when precision >= 4 and precision <= 18 do
    tuple_size(elem(@raw_estimate_data, precision - 4))
  end
end
"""

output_path = "lib/fate/cardinality/hyperloglog/bias_data.ex"
File.write!(output_path, module_source)
IO.puts("\nGenerated #{output_path}")
